credentials:
  usernames:
    ritishm:
      email: jsmith@gmail.com
      name: Ritish Mohapatra
      password: '$2b$12$5vNVuuf0x0vkxt42RMgW1.TS5AU9i.9cCXyZwakV7FT5TlroogCq2'
    ritishm:
      email: jsmith@gmail.com
      name: Biswajit Biswal
      password: '$2b$12$5vNVuuf0x0vkxt42RMgW1.TS5AU9i.9cCXyZwakV7FT5TlroogCq2'
    ritishm:
      email: jsmith@gmail.com
      name: Samaya Kumar Muduli
      password: '$2b$12$5vNVuuf0x0vkxt42RMgW1.TS5AU9i.9cCXyZwakV7FT5TlroogCq2'
    satyar:
      email: rbriggs@gmail.com
      name: Satyajit Rout
      password: '$2b$12$PACp1JYR8UXBG91eHHedieAbNjjqmtf5yOGhKWSO4AM9rtbV3v6GS'
cookie:
  expiry_days: 2
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com