branch-defaults:
  main:
    environment: onboarding-automation-ui
    group_suffix: null
global:
  application_name: onboarding-automation
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
